[package]
name = "crypto-cli-tools"
version = "0.3.9"
edition = "2021"
authors = ["soulmachine <soulmachine@gmail.com>"]
description = "A collection of CLI tools to process cryptocurrency data"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-cli-tools"
keywords = ["cryptocurrency", "blockchain", "trading"]


[dependencies]
chrono = "0.4"
crypto-msg-parser = "1.4.9"
crypto-pair = "2.0.6"
dashmap = "4"
env_logger = "0.8"
flate2 = "1"
glob = "0.3"
num_cpus = "1"
log = "0.4"
rand = "0.8.4"
regex = "1"
rlimit = "0.6.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
threadpool = "1"
xz2 = "0.1"

[profile.release]
lto = true
codegen-units = 1
