[package]
name = "crypto-cli-tools"
version = "0.1.1"
edition = "2021"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "A collection of CLI tools to process cryptocurrency data"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-cli-tools"
keywords = ["cryptocurrency", "blockchain", "trading"]


[dependencies]
crypto-msg-parser = "1.4.1"
flate2 = "1"
serde_json = "1.0"
xz2 = "0.1"
