[package]
name = "crypto-cli-tools"
version = "0.7.3"
edition = "2021"
authors = ["soulmachine <soulmachine@gmail.com>"]
description = "A collection of CLI tools to process cryptocurrency data"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-cli-tools"
keywords = ["cryptocurrency", "blockchain", "trading"]


[dependencies]
chrono = "0.4.19"
crypto-market-type = "1.0.9"
crypto-msg-parser = "1.9.9"
crypto-msg-type = "1.0.6"
crypto-pair = "2.2.2"
dashmap = "5.2.0"
env_logger = "0.9.0"
flate2 = "1.0.22"
glob = "0.3.0"
num_cpus = "1.13.1"
log = "0.4.16"
rand = "0.8.5"
regex = "1.5.5"
rlimit = "0.7.0"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
sysinfo = "0.23.5"
threadpool = "1.8.1"
xz2 = "0.1.6"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1
opt-level="z"
